import {
  AlertCircle,
  AlertTriangle,
  Award,
  CalendarPlus,
  Layers,
  MapPin,
  MessageCircle,
  MessageSquarePlus,
  Receipt,
  Sparkles,
  Trophy,
  TrendingDown,
  UserPlus,
  Users,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const DAGENS_FOKUS_ICON_MAP: Record<string, LucideIcon> = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  award: Award,
  "calendar-plus": CalendarPlus,
  layers: Layers,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square-plus": MessageSquarePlus,
  receipt: Receipt,
  sparkles: Sparkles,
  trophy: Trophy,
  "trending-down": TrendingDown,
  "user-plus": UserPlus,
  users: Users,
  zap: Zap,
};
