import { createClient } from '@supabase/supabase-js';

const sb = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_KEY!);

const drills = [
  // ── PUTTING (32) ──────────────────────────────────────────
  {name:'DECADE: Yard Stick Putting',description:'Putt along a yard stick. Ball must stay on it.',goal:'Start putts on correct line',duration_minutes:10,pyramid_level:'TEK',training_areas:['PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting'],sg_area:'putting'},
  {name:'DECADE: Two-Putt Drill',description:'Make 6 two-putts in a row from 40ft+. 3-putt = start over.',goal:'Eliminate 3-putts from long range',duration_minutes:30,pyramid_level:'TEK',training_areas:['PUTT40+'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','lag'],sg_area:'putting'},
  {name:'DECADE: Tornado Drill',description:'Tees at 2-8ft around hole. Make 1 from each in a row. Miss = restart.',goal:'Short putt consistency under pressure',duration_minutes:30,pyramid_level:'TEK',training_areas:['PUTT0-3','PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','press'],sg_area:'putting'},
  {name:'DECADE: Tech Drill',description:'Tees at 4-5ft at 2,6,9,12 oclock. Make all 8 in a row x2. Miss = restart.',goal:'Clock putting from all angles',duration_minutes:25,pyramid_level:'TEK',training_areas:['PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','clock'],sg_area:'putting'},
  {name:'DECADE: Speed Putting',description:'From 3ft, roll to hit back, middle, front of hole. 10 times.',goal:'Speed control on short putts',duration_minutes:10,pyramid_level:'TEK',training_areas:['PUTT0-3'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','speed'],sg_area:'putting'},
  {name:'DECADE: Speed Control Fringe',description:'4 balls center green. Putt to fringe all 4 directions within putter length.',goal:'Lag putting distance control all directions',duration_minutes:20,pyramid_level:'TEK',training_areas:['PUTT25-40','PUTT40+'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','lag'],sg_area:'putting'},
  {name:'DECADE: Short Putt Confidence',description:'Make 10 in a row from 3ft before you play.',goal:'Pre-round confidence on short putts',duration_minutes:5,pyramid_level:'TEK',training_areas:['PUTT0-3'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'nybegynner',source:'external',source_author:'DECADE Golf',tags:['decade','putting','confidence'],sg_area:'putting'},
  {name:'DECADE: Row Putting',description:'Make 12 in a row: 2@2ft, 3@3ft, 3@4ft, 3@5ft, 1@6ft. Miss = restart.',goal:'Progressive short putt pressure',duration_minutes:25,pyramid_level:'TEK',training_areas:['PUTT0-3','PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','press'],sg_area:'putting'},
  {name:'DECADE: Putt Until You Make',description:'Make from 15,20,25,30,35,40ft. Full routine each putt.',goal:'Long putt making with routine',duration_minutes:45,pyramid_level:'SLAG',training_areas:['PUTT15-25','PUTT25-40','PUTT40+'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','long'],sg_area:'putting'},
  {name:'DECADE: Putt to a Tee',description:'Tee in ground, putt from 3ft. Count hits on tee.',goal:'Extreme precision aim small miss small',duration_minutes:15,pyramid_level:'TEK',training_areas:['PUTT0-3'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','precision'],sg_area:'putting'},
  {name:'DECADE: Putting with SW',description:'Make 10 from 3ft using sand wedge leading edge.',goal:'Face control with unfamiliar tool',duration_minutes:15,pyramid_level:'TEK',training_areas:['PUTT0-3'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting'],sg_area:'putting'},
  {name:'DECADE: Jumping Jacks Putting',description:'30 sec jumping jacks then make 5 five-footers in a row.',goal:'Putt under physiological stress',duration_minutes:10,pyramid_level:'TURN',training_areas:['PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','mental'],sg_area:'putting'},
  {name:'DECADE: Pro-Side Putting',description:'Tee in front of hole. Breaking 4-5ft putt. Keep ball above tee.',goal:'Pro-side bias on breaking putts',duration_minutes:5,pyramid_level:'TEK',training_areas:['PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','break'],sg_area:'putting'},
  {name:'DECADE: Coin Drill',description:'Coin in front of hole. Make 5 from 3,4,5ft rolling over coin. Miss coin = restart.',goal:'Extreme start line precision',duration_minutes:15,pyramid_level:'TEK',training_areas:['PUTT0-3','PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','precision'],sg_area:'putting'},
  {name:'DECADE: Green Reading 2',description:'4 balls opposite sides of hole. Read each putt, count correct reads.',goal:'Green reading accuracy multiple angles',duration_minutes:5,pyramid_level:'TEK',training_areas:['PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','green-reading'],sg_area:'putting'},
  {name:'DECADE: Gate Drill 100 Putts',description:'2 tees off toe/heel. 10 right hand, 10 both hands. Goal: 100 from 3ft.',goal:'Gate putting face alignment',duration_minutes:45,pyramid_level:'TEK',training_areas:['PUTT0-3'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','gate'],sg_area:'putting'},
  {name:'DECADE: Faceoff Putting',description:'2 balls side by side. Putt both. If one leads, face was open/closed.',goal:'Diagnose face angle at impact',duration_minutes:10,pyramid_level:'TEK',training_areas:['PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','diagnostikk'],sg_area:'putting'},
  {name:'DECADE: Drawbacks Putting',description:'18 holes putting. Draw back putter length unless you make it.',goal:'Aggressive putting reward makes',duration_minutes:20,pyramid_level:'SLAG',training_areas:['PUTT5-10','PUTT10-15','PUTT15-25'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','aggressiv'],sg_area:'putting'},
  {name:'DECADE: Makes 18 Putts',description:'18 putts from 10-25ft. Score par 2 per hole.',goal:'Mid-range putt conversion tracking',duration_minutes:15,pyramid_level:'SLAG',training_areas:['PUTT10-15','PUTT15-25'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','makes'],sg_area:'putting'},
  {name:'DECADE: Minus 5 Putting',description:'From 5ft only. First putt birdie, second par. Reach 5 under.',goal:'Short putt scoring mentality',duration_minutes:25,pyramid_level:'SLAG',training_areas:['PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','scoring'],sg_area:'putting'},
  {name:'DECADE: Lag Putting',description:'3 balls 20ft+ to 3 holes. Repeat 3x. Count 2-putts of 9.',goal:'Lag putting varied distances',duration_minutes:10,pyramid_level:'TEK',training_areas:['PUTT15-25','PUTT25-40'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','lag'],sg_area:'putting'},
  {name:'DECADE: Circle Drill',description:'6 balls around hole. Make all from 2ft, 4ft, 6ft. All 18 in a row.',goal:'360-degree short putt mastery',duration_minutes:45,pyramid_level:'TEK',training_areas:['PUTT0-3','PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','circle'],sg_area:'putting'},
  {name:'DECADE: Clock Drill',description:'Tees at 4-5ft at 2,6,9,12 oclock. Make all 8 in a row x2.',goal:'Clock putting consistency',duration_minutes:25,pyramid_level:'TEK',training_areas:['PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','clock'],sg_area:'putting'},
  {name:'DECADE: Chalk Line',description:'Chalk line on green on straight putt. Roll ball on the line.',goal:'Check alignment and stroke path',duration_minutes:10,pyramid_level:'TEK',training_areas:['PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'nybegynner',source:'external',source_author:'DECADE Golf',tags:['decade','putting','alignment'],sg_area:'putting'},
  {name:'DECADE: 80 Putts',description:'30@3ft, 25@4ft, 10@5ft, 10@6ft, 5@10ft. Goal: 74 one-putts.',goal:'Volume short putt training with scoring',duration_minutes:30,pyramid_level:'SLAG',training_areas:['PUTT0-3','PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','volume'],sg_area:'putting'},
  {name:'DECADE: 3-6 Foot Drill',description:'3@3ft, 3@4ft, 3@5ft, 1@6ft. Count makes of 10.',goal:'Short putt baseline test',duration_minutes:5,pyramid_level:'TEK',training_areas:['PUTT0-3','PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'nybegynner',source:'external',source_author:'DECADE Golf',tags:['decade','putting','test'],sg_area:'putting'},
  {name:'DECADE: 8ft Putts',description:'12 eight-foot putts. Count makes.',goal:'Mid-range putt baseline',duration_minutes:5,pyramid_level:'TEK',training_areas:['PUTT5-10'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','test'],sg_area:'putting'},
  {name:'DECADE: 10ft Putts',description:'12 ten-foot putts. Count makes.',goal:'10ft putt conversion rate',duration_minutes:5,pyramid_level:'TEK',training_areas:['PUTT5-10','PUTT10-15'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','test'],sg_area:'putting'},
  {name:'DECADE: 15ft Putts',description:'3 different 15ft putts. 3 balls each into hole or past within grip length.',goal:'15ft putt consistency',duration_minutes:15,pyramid_level:'TEK',training_areas:['PUTT10-15','PUTT15-25'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','mid-range'],sg_area:'putting'},
  {name:'DECADE: 3 4 5 Drill',description:'6@3ft, 4@4ft, 2@5ft in a row. Miss = restart.',goal:'Progressive pressure short putting',duration_minutes:20,pyramid_level:'TEK',training_areas:['PUTT0-3','PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','putting','press'],sg_area:'putting'},
  {name:'DECADE: 18 Two-Putts',description:'From 20,30,40ft. Must 2-putt 18 holes in a row. Full routine.',goal:'Lag putt elimination of 3-putts',duration_minutes:15,pyramid_level:'TEK',training_areas:['PUTT15-25','PUTT25-40','PUTT40+'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','lag'],sg_area:'putting'},
  {name:'DECADE: 3 Footers x50',description:'See how many 3-footers you make out of 50.',goal:'Short putt volume and tracking',duration_minutes:20,pyramid_level:'SLAG',training_areas:['PUTT0-3'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'nybegynner',source:'external',source_author:'DECADE Golf',tags:['decade','putting','volume'],sg_area:'putting'},
  {name:'DECADE: Angles Putting',description:'3 balls from 10,15,20ft from 6 angles. 18 putts, goal score 30.',goal:'Putt from varied angles and distances',duration_minutes:30,pyramid_level:'SLAG',training_areas:['PUTT5-10','PUTT10-15','PUTT15-25'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','putting','angles'],sg_area:'putting'},
  // ── APPROACH / WEDGE (11) ─────────────────────────────────
  {name:'DECADE: Wedge 30 Ball Scatter',description:'30 balls 30-120 yds. Hit to green with full routine. Goal: 25 greens.',goal:'Wedge precision varied distances',duration_minutes:45,pyramid_level:'SLAG',training_areas:['INN100','INN50'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','wedge'],sg_area:'approach'},
  {name:'DECADE: Wedge Pyramid',description:'Start 50yds, work to 100. Move on when within 3yds of target.',goal:'Progressive wedge distance control',duration_minutes:45,pyramid_level:'SLAG',training_areas:['INN100','INN50'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','wedge'],sg_area:'approach'},
  {name:'DECADE: Wedge Challenge',description:'3 balls every 10yds from 40-110. Random order. Track greens of 40.',goal:'Random wedge distance simulation',duration_minutes:25,pyramid_level:'SLAG',training_areas:['INN100','INN50'],l_phases:['L-AUTO'],environments:['M2'],press_levels:['PR3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','wedge'],sg_area:'approach'},
  {name:'DECADE: On the 5s',description:'5 balls at 45,55,65,75yds etc. Score of 40.',goal:'Systematic wedge distance ladder',duration_minutes:25,pyramid_level:'SLAG',training_areas:['INN50','INN100'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','wedge'],sg_area:'approach'},
  {name:'DECADE: Pin Seeker 90-120',description:'Approach shots to flag with different flights. Land on green.',goal:'Approach precision shot variation',duration_minutes:25,pyramid_level:'SLAG',training_areas:['INN100'],l_phases:['L-AUTO'],environments:['M2'],press_levels:['PR3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','approach'],sg_area:'approach'},
  {name:'DECADE: Grip Downs',description:'Targets at 120,150yds. 1 club more grip down. 10 each. Score of 20.',goal:'Distance control with grip-down',duration_minutes:25,pyramid_level:'SLAG',training_areas:['INN100','INN150'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','approach'],sg_area:'approach'},
  {name:'DECADE: 110 Yard Drill',description:'5 balls at 40,50,60...110yds. Track greens. Goal: 24/40.',goal:'Full wedge range test',duration_minutes:25,pyramid_level:'SLAG',training_areas:['INN50','INN100'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','wedge','test'],sg_area:'approach'},
  {name:'DECADE: 100 Yard Shot',description:'20 shots to 100yd target within 20ft radius.',goal:'Stock 100 yard precision',duration_minutes:5,pyramid_level:'SLAG',training_areas:['INN100'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','wedge'],sg_area:'approach'},
  {name:'DECADE: 88 Shot Challenge',description:'Full routine every shot. Shot shapes 7i-4i. Finish 10 normal 6i.',goal:'Full bag approach with routine',duration_minutes:60,pyramid_level:'SLAG',training_areas:['INN150','INN200'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','approach'],sg_area:'approach'},
  // ── SHORT GAME (14) ──────────────────────────────────────
  {name:'DECADE: Up and Down Club Challenge',description:'12 balls off green. Up and down with SW,PW,9i,8i,7i,Hybrid.',goal:'Short game versatility multiple clubs',duration_minutes:30,pyramid_level:'SLAG',training_areas:['CHIP','PITCH'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','short-game'],sg_area:'short_game'},
  {name:'DECADE: Shafts',description:'4 shafts 2-3ft apart on green. Hit ball in each gap. Miss = restart.',goal:'Precision landing short game',duration_minutes:20,pyramid_level:'SLAG',training_areas:['CHIP','PITCH'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','short-game'],sg_area:'short_game'},
  {name:'DECADE: Landing Spots',description:'3 balls off green. Tee at landing spot. Count club-length landings x9.',goal:'Consistent landing zones chipping',duration_minutes:5,pyramid_level:'TEK',training_areas:['CHIP','PITCH'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','chipping'],sg_area:'short_game'},
  {name:'DECADE: High/Low Short Game',description:'Same pin same position. Play high and low. 20 times.',goal:'Trajectory versatility short game',duration_minutes:10,pyramid_level:'TEK',training_areas:['CHIP','PITCH'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','short-game'],sg_area:'short_game'},
  {name:'DECADE: Flagstick Drill',description:'20 balls around practice green. Count within flagstick length.',goal:'Short game precision all positions',duration_minutes:25,pyramid_level:'SLAG',training_areas:['CHIP','PITCH','BUNKER'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','short-game'],sg_area:'short_game'},
  {name:'DECADE: Drops Chipping',description:'20 balls around chipping green. Count within flagstick length.',goal:'Chipping precision random positions',duration_minutes:15,pyramid_level:'SLAG',training_areas:['CHIP','PITCH'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','chipping'],sg_area:'short_game'},
  {name:'DECADE: 9 Easy Chips',description:'9 easy chips 1-3 paces off green. 5 balls each. Get 3/5 up and down.',goal:'Basic chip consistency',duration_minutes:20,pyramid_level:'SLAG',training_areas:['CHIP'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','chipping'],sg_area:'short_game'},
  {name:'DECADE: 9 Hole Up and Downs',description:'9 locations around green. 1 ball each. Goal: 7/9 up and down.',goal:'Scrambling varied positions',duration_minutes:30,pyramid_level:'SLAG',training_areas:['CHIP','PITCH','PUTT3-5'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','short-game'],sg_area:'short_game'},
  {name:'DECADE: 6s Short Game',description:'18 holes up/downs. 6 easy, 6 medium, 6 hard.',goal:'Short game scoring all difficulties',duration_minutes:20,pyramid_level:'SLAG',training_areas:['CHIP','PITCH'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','short-game'],sg_area:'short_game'},
  {name:'DECADE: +1 Drill',description:'10 chips 15-20ft. Chip in=-1, one putt=0, two putt=+1.',goal:'Chip and putt scoring pressure',duration_minutes:20,pyramid_level:'SLAG',training_areas:['CHIP'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','chipping'],sg_area:'short_game'},
  {name:'DECADE: Houston Bunker',description:'Throw 10 balls in bunker random lies. Count up and downs.',goal:'Bunker scrambling random lies',duration_minutes:30,pyramid_level:'SLAG',training_areas:['BUNKER'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','bunker'],sg_area:'short_game'},
  {name:'DECADE: High/Low Bunker',description:'10 low, 10 high out of bunker to different pins.',goal:'Bunker trajectory control',duration_minutes:10,pyramid_level:'SLAG',training_areas:['BUNKER'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','bunker'],sg_area:'short_game'},
  {name:'DECADE: Closer Bunker',description:'Bunker to pin not past. Each ball closer than last. Past = game over.',goal:'Bunker distance control progressive',duration_minutes:20,pyramid_level:'SLAG',training_areas:['BUNKER'],l_phases:['L-AUTO'],environments:['M3'],press_levels:['PR3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','bunker'],sg_area:'short_game'},
  {name:'DECADE: Buried Lies',description:'10 balls buried in bunker. Get at least 5 on green.',goal:'Escape from buried bunker lies',duration_minutes:15,pyramid_level:'SLAG',training_areas:['BUNKER'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','bunker'],sg_area:'short_game'},
  // ── TEE SHOTS (6) ────────────────────────────────────────
  {name:'DECADE: Target Practice Tee',description:'10 tee shots starting ball at target. Count successful starts.',goal:'Driver start line accuracy',duration_minutes:15,pyramid_level:'SLAG',training_areas:['TEE'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','driver'],sg_area:'tee'},
  {name:'DECADE: Low/High Tee Shots',description:'30 balls alternating high and low drivers.',goal:'Driver trajectory control',duration_minutes:30,pyramid_level:'SLAG',training_areas:['TEE'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','driver'],sg_area:'tee'},
  {name:'DECADE: Flight Control Driver',description:'10 right-to-left, 10 left-to-right drivers.',goal:'Driver shot shape on command',duration_minutes:25,pyramid_level:'SLAG',training_areas:['TEE'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','driver'],sg_area:'tee'},
  {name:'DECADE: Driver Accuracy 15',description:'2 markers as fairway. 15 drivers. Count fairways.',goal:'Driver fairway percentage',duration_minutes:15,pyramid_level:'SLAG',training_areas:['TEE'],l_phases:['L-AUTO'],environments:['M2'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','driver'],sg_area:'tee'},
  {name:'DECADE: Add-on Driver',description:'14 balls through markers. Miss = add a ball. Hit til out.',goal:'Driver accuracy under pressure',duration_minutes:20,pyramid_level:'SLAG',training_areas:['TEE'],l_phases:['L-AUTO'],environments:['M2'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','driver'],sg_area:'tee'},
  {name:'DECADE: Bunker Pin Length',description:'Short bunker shot. Count within pin length (7ft) of 10.',goal:'Bunker precision short shots',duration_minutes:5,pyramid_level:'SLAG',training_areas:['BUNKER'],l_phases:['L-AUTO'],environments:['M3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','bunker'],sg_area:'short_game'},
  // ── ON COURSE (9) ────────────────────────────────────────
  {name:'DECADE: Worst Ball',description:'9/18 holes. Play 2 balls, take worst. Score vs par.',goal:'Consistency test eliminate weak shots',duration_minutes:120,pyramid_level:'SPILL',training_areas:['TEE','INN150','INN100','CHIP','PUTT5-10'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','on-course']},
  {name:'DECADE: Best Ball',description:'9/18 holes. Play 2 balls, take best.',goal:'Confidence building best-ball scoring',duration_minutes:140,pyramid_level:'SPILL',training_areas:['TEE','INN150','INN100','CHIP','PUTT5-10'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','on-course']},
  {name:'DECADE: Position Z',description:'18 holes bad positions on purpose. Try to make par.',goal:'Recovery shot creativity',duration_minutes:180,pyramid_level:'SPILL',training_areas:['CHIP','PITCH','LOB','BUNKER'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','on-course'],sg_area:'short_game'},
  {name:'DECADE: Pick-up and Drop',description:'18 holes pick up on green, drop 3 paces off. Make up and down.',goal:'Short game scoring every position',duration_minutes:240,pyramid_level:'SPILL',training_areas:['CHIP','PITCH','PUTT3-5','PUTT5-10'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','on-course'],sg_area:'short_game'},
  {name:'DECADE: Misses',description:'18 holes miss every green. Track up and downs.',goal:'Forced scrambling practice',duration_minutes:240,pyramid_level:'SPILL',training_areas:['TEE','CHIP','PITCH','BUNKER','PUTT3-5'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','on-course'],sg_area:'short_game'},
  {name:'DECADE: Forward Tees',description:'Play from red tees. No bogeys. Goal: 6+ birdies.',goal:'Scoring from short positions',duration_minutes:140,pyramid_level:'SPILL',training_areas:['TEE','INN50','INN100','PUTT5-10'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','on-course'],sg_area:'approach'},
  {name:'DECADE: On Course Driving',description:'2 balls off each tee: driver and 3-wood. Count in play.',goal:'Compare driver vs 3-wood on course',duration_minutes:120,pyramid_level:'SPILL',training_areas:['TEE'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR3'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','on-course'],sg_area:'tee'},
  {name:'DECADE: Drives and 5s',description:'2 drives per tee. Score fairway/miss/trees. Wedge and chip.',goal:'Combined driving and short game',duration_minutes:240,pyramid_level:'SPILL',training_areas:['TEE','INN100','CHIP'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR4'],difficulty:'regional',source:'external',source_author:'DECADE Golf',tags:['decade','on-course']},
  {name:'DECADE: 9 Hole Par 3',description:'Play par 3 course until under par.',goal:'Short approach scoring challenge',duration_minutes:120,pyramid_level:'SPILL',training_areas:['INN50','INN100'],l_phases:['L-AUTO'],environments:['M4'],press_levels:['PR4'],difficulty:'klubb',source:'external',source_author:'DECADE Golf',tags:['decade','on-course'],sg_area:'approach'},
];

async function run() {
  console.log(`Importerer ${drills.length} DECADE-driller...`);
  const { data, error } = await sb.from('drills').insert(
    drills.map(d => ({ ...d, is_approved: false, is_active: true }))
  ).select('id, name');
  if (error) { console.error('FEIL:', error.message); process.exit(1); }
  console.log(`✓ ${data.length} driller importert (unapproved — klar for review)`);
  const byPyr: Record<string,number> = {};
  drills.forEach(d => byPyr[d.pyramid_level] = (byPyr[d.pyramid_level]||0)+1);
  console.log('Fordeling:', JSON.stringify(byPyr));
}
run();
