#!/bin/bash
# AK Golf MCP Server — Setup Guide
# Kjør dette steg for steg. Ikke som script.

echo "=== AK Golf MCP Server Setup ==="
echo ""
echo "STEG 1: Sett miljøvariabler"
echo "  export SUPABASE_URL='https://din-prosjekt.supabase.co'"
echo "  export SUPABASE_SERVICE_KEY='din-service-role-key'"
echo ""
echo "STEG 2: Kjør database-migrering i Supabase SQL Editor"
echo "  Åpne: https://supabase.com/dashboard/project/DITT-PROSJEKT/sql/new"
echo "  Lim inn: supabase/migrations/001_initial_schema.sql"
echo "  Kjør."
echo ""
echo "STEG 3: Seed drill-biblioteket"
echo "  Lim inn: supabase/seeds/001_drills_seed.sql"
echo "  Kjør."
echo ""
echo "STEG 4: (Valgfritt) Seed testspillere"
echo "  Lim inn: supabase/seeds/002_sample_players.sql"
echo "  Kjør."
echo ""
echo "STEG 5: Installer og bygg"
echo "  npm install"
echo "  npm run build"
echo ""
echo "STEG 6: Start serveren"
echo "  npm start                     # stdio (Claude Desktop / Claude Code)"
echo "  TRANSPORT=http npm start      # HTTP (remote / claude.ai)"
echo ""
echo "STEG 7: Test med MCP Inspector"
echo "  npx @modelcontextprotocol/inspector"
echo ""
echo "=== Ferdig! ==="
