import type { KColumnData } from "./types";

// TODO: koble til ekte data — CoachingSession + status-felt i Prisma.
export const MOCK_COLUMNS: KColumnData[] = [
  {
    key: "preparation",
    title: "Forberedelse",
    count: 6,
    icon: "clipboard-list",
    cards: [
      {
        id: "p1",
        studentName: "Sofie Holm",
        studentInitials: "SH",
        avatarColor: "#6FCBA1",
        when: "TIR 14:00",
        focus:
          "Driver-tempo · forberede TrackMan-protokoll basert på siste 3 runder",
        progress: 60,
        metaLabel: "3/5 steg",
        attachments: 2,
        comments: 1,
      },
      {
        id: "p2",
        studentName: "Emma Lien",
        studentInitials: "EL",
        avatarColor: "#E8B967",
        when: "TIR 17:00",
        focus:
          "Fullswing-eval · ikke logget runder på 14d. Trenger re-engagement-plan først",
        progress: 20,
        metaLabel: "1/5 · Forfaller 16:30",
        state: "urgent",
        trailingIcon: "alert-triangle",
      },
      {
        id: "p3",
        studentName: "Lars Berg",
        studentInitials: "LB",
        avatarColor: "#6FB3FF",
        when: "ONS 09:00",
        focus: "Iron-tempo · etter forrige økt. Klubbe-distance review",
        progress: 40,
        metaLabel: "2/5 steg",
        attachments: 1,
      },
      {
        id: "p4",
        studentName: "Camilla R.",
        studentInitials: "CR",
        avatarColor: "#C896E8",
        when: "ONS 13:00",
        focus: "Putting-stroke · drift høyre — rotasjons-test før økt",
        progress: 80,
        metaLabel: "4/5 steg",
        attachments: 3,
        comments: 2,
      },
      {
        id: "p5",
        studentName: "Henrik Vold",
        studentInitials: "HV",
        avatarColor: "#F49283",
        when: "MAN 15:30",
        focus: "Banecoaching · 9 hull · course management og strategi",
        progress: 100,
        metaLabel: "5/5 ✓ Klar",
        state: "ready",
        trailingIcon: "check-circle",
      },
      {
        id: "p6",
        studentName: "Junior Group A",
        studentInitials: "JG",
        avatarColor: "#D1F843",
        when: "MAN 18:30",
        focus: "Kveldstrening · 8 stk · ferdighetsrotasjon 4 stasjoner",
        progress: 70,
        metaLabel: "Markus assist",
        trailingIcon: "users",
      },
    ],
  },
  {
    key: "active",
    title: "Pågår",
    count: 1,
    icon: "zap",
    cards: [
      {
        id: "a1",
        studentName: "Markus Eide",
        studentInitials: "ME",
        avatarColor: "#D1F843",
        when: "14:00 NÅ",
        focus: "Putting · lag-styring · TrackMan logger live · 32 min igjen",
        progress: 47,
        metaLabel: "Putting Green · Live",
        state: "live",
        trailingIcon: "circle-dot",
      },
    ],
  },
  {
    key: "followup",
    title: "Etterarbeid",
    count: 5,
    icon: "edit-3",
    cards: [
      {
        id: "f1",
        studentName: "Erik Lund",
        studentInitials: "EL",
        avatarColor: "#6FCBA1",
        when: "MAN 09:30",
        focus: "Iron consistency · skrive opp-summering, sende kveldsplan",
        progress: 50,
        metaLabel: "2/4 oppgaver",
        trailingIcon: "file-text",
      },
      {
        id: "f2",
        studentName: "Sofie Holm",
        studentInitials: "SH",
        avatarColor: "#6FCBA1",
        when: "MAN 07:00",
        focus: "Driver · TrackMan eksportert · skrive AI-narrative + dele",
        progress: 75,
        metaLabel: "3/4 oppgaver",
        trailingIcon: "sparkles",
      },
      {
        id: "f3",
        studentName: "Mia Dahl",
        studentInitials: "MD",
        avatarColor: "#E8B967",
        when: "FRE 25 apr",
        focus: "Range-økt · venter på spiller-svar på hjemmeoppgave",
        progress: 85,
        metaLabel: "Venter spiller",
        trailingIcon: "clock",
      },
      {
        id: "f4",
        studentName: "Junior B",
        studentInitials: "JG",
        avatarColor: "#C896E8",
        when: "FRE 25 apr",
        focus: "8 stk · sende foreldre-rapport via e-post",
        progress: 30,
        metaLabel: "Mal ikke ferdig",
        trailingIcon: "mail",
      },
      {
        id: "f5",
        studentName: "Kari Nord",
        studentInitials: "KN",
        avatarColor: "#6FB3FF",
        when: "TOR 24 apr",
        focus: "Studio-økt · oppdater spillerprofil + neste mål",
        progress: 60,
        metaLabel: "3/5 oppgaver",
        trailingIcon: "user",
      },
    ],
  },
  {
    key: "done",
    title: "Ferdig",
    count: 12,
    icon: "check-circle-2",
    cards: [
      {
        id: "d1",
        studentName: "Pelle K.",
        studentInitials: "PK",
        avatarColor: "#6FCBA1",
        when: "FRE 25",
        focus: "Studio · Iron-tempo · plan sendt + faktura",
        metaLabel: "Lukket fre 18:24",
        state: "done",
        trailingIcon: "check",
      },
      {
        id: "d2",
        studentName: "Anne M.",
        studentInitials: "AM",
        avatarColor: "#6FCBA1",
        when: "TOR 24",
        focus: "Studio · Fullswing · alle aksjoner ferdig",
        metaLabel: "Lukket tor 20:11",
        state: "done",
        trailingIcon: "check",
      },
      {
        id: "d3",
        studentName: "Tor Solberg",
        studentInitials: "TS",
        avatarColor: "#6FCBA1",
        when: "TOR 24",
        focus: "Bane 9 hull · narrativ + neste plan ferdig",
        metaLabel: "Lukket tor 17:55",
        state: "done",
        trailingIcon: "check",
      },
      {
        id: "d4",
        studentName: "9 flere lukket",
        studentInitials: "+9",
        avatarColor: "#7A8C85",
        when: "UKE 17",
        focus: "",
        metaLabel: "Vis arkiv →",
        state: "archive",
        trailingIcon: "archive",
      },
    ],
  },
];
