// AK Golf Academy — Drill Library Seed
// Generates drills directly from Masterdokument v2.0 methodology
// Run: npx tsx scripts/seed-drills.ts

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY!;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Sett SUPABASE_URL og SUPABASE_SERVICE_KEY først.');
  process.exit(1);
}

const sb = createClient(SUPABASE_URL, SUPABASE_KEY);

// ════════════════════════════════════════════════════════════
// DRILLS — direkte fra AK Masterdokument v2.0
// ════════════════════════════════════════════════════════════

const drills = [

  // ── TEK: FULL SWING ───────────────────────────────────────

  {
    name: 'Speil-drill: P5.0-P6.0 Transition',
    description: 'Stå foran speil eller bruk video. Kjør sakte gjennomføring av transition fra topp (P4.0) til delivery (P6.0). Ingen kølle. Fokus på sekvens: hofte starter, overkropp følger, armer sist.',
    goal: 'Etablere korrekt downswing-sekvens uten fart',
    instructions: '1. Setup foran speil i address\n2. Sving til P4.0 (topp)\n3. Start nedover: hofte roterer først\n4. Sjekk P5.0: lead arm parallelt med bakken\n5. Sjekk P6.0: skaft parallelt med bakken\n6. Hold P6.0 i 3 sekunder\n7. Gjenta 15 ganger',
    duration_minutes: 15,
    pyramid_level: 'TEK',
    training_areas: ['TEE', 'INN200', 'INN150'],
    l_phases: ['L-KROPP', 'L-ARM'],
    cs_min: 'CS0',
    cs_max: 'CS30',
    environments: ['M0', 'M1'],
    press_levels: ['PR1'],
    p_positions: ['P4.0', 'P5.0', 'P6.0'],
    life_codes: ['LIFE-SELV'],
    min_category: 'K',
    max_category: 'A',
    difficulty: 'nybegynner',
    equipment: ['Speil eller video'],
    players_min: 1, players_max: 1,
    trackman_metrics: ['club_path', 'attack_angle'],
    source: 'ak_original',
    tags: ['transition', 'sekvens', 'grunnleggende', 'videoanalyse'],
    sg_area: 'tee',
    is_approved: true,
  },
  {
    name: 'Halvsvinger med alignment sticks — P2.0-P8.0',
    description: 'Plasser alignment stick langs tålinjen og én parallelt 2m foran. Slå halvsvinger med 7-jern på CS50. Sjekk at køllehode følger target-linje gjennom P7.0.',
    goal: 'Overføre teknisk bevegelse til balltrening med lav hastighet',
    instructions: '1. Legg alignment stick langs tålinjen\n2. Legg stick 2m foran parallelt\n3. Ta halvsvinger P2.0 til P8.0\n4. CS50: halvparten av maks hastighet\n5. Fokus: køllehode peker langs target på P2.0 og P8.0\n6. 20 baller, pause mellom hver',
    duration_minutes: 20,
    pyramid_level: 'TEK',
    training_areas: ['TEE', 'INN150', 'INN100'],
    l_phases: ['L-BALL'],
    cs_min: 'CS40',
    cs_max: 'CS60',
    environments: ['M1', 'M2'],
    press_levels: ['PR1', 'PR2'],
    p_positions: ['P2.0', 'P7.0', 'P8.0'],
    life_codes: ['LIFE-SELV'],
    min_category: 'I',
    max_category: 'A',
    difficulty: 'rekrutt',
    equipment: ['Alignment sticks', '7-jern', 'Baller'],
    players_min: 1, players_max: 2,
    trackman_metrics: ['club_path', 'face_angle', 'face_to_path'],
    source: 'ak_original',
    tags: ['halvsvinger', 'alignment', 'path', 'face'],
    sg_area: 'approach',
    is_approved: true,
  },
  {
    name: 'Impact bag — P6.5-P7.0 posisjon',
    description: 'Bruk impact bag eller stablet håndklær. Slow motion sving til impact (P7.0). Hold posisjonen og sjekk: hender foran ball, hofte åpen, vekt på lead-fot.',
    goal: 'Bygge korrekt impact-posisjon som muskelminne',
    instructions: '1. Plasser impact bag på ballen sin posisjon\n2. Setup normalt med 7-jern\n3. Sving til P7.0 i slow motion (CS20-30)\n4. Press inn i bagen og HOLD\n5. Sjekk: shaft lean, hofte åpen, vekt fremover\n6. 3 sett × 10 repetitions',
    duration_minutes: 15,
    pyramid_level: 'TEK',
    training_areas: ['TEE', 'INN150', 'INN100', 'INN50'],
    l_phases: ['L-KØLLE'],
    cs_min: 'CS20',
    cs_max: 'CS40',
    environments: ['M0', 'M1', 'M2'],
    press_levels: ['PR1'],
    p_positions: ['P6.5', 'P7.0'],
    min_category: 'K',
    max_category: 'B',
    difficulty: 'nybegynner',
    equipment: ['Impact bag eller håndklær', 'Jern'],
    players_min: 1, players_max: 4,
    trackman_metrics: ['attack_angle', 'face_angle'],
    source: 'ak_original',
    tags: ['impact', 'posisjon', 'slow-motion', 'grunnleggende'],
    sg_area: 'approach',
    is_approved: true,
  },
  {
    name: 'Speed Ladder — CS60→CS80→CS100 driver',
    description: 'Progressiv hastighetsøkning med driver. Start CS60, øk til CS80, toppes på CS100. Overvåk at teknikk holder ved hvert nivå. Identifiser breaking point.',
    goal: 'Finne CS breaking point og trene overføring fra TEK til SLAG',
    instructions: '1. 5 slag på CS60 — fokus på posisjon\n2. 5 slag på CS70 — føl endringen\n3. 5 slag på CS80 — begynner det å bryte?\n4. 3 slag på CS90 — noter hva som endrer seg\n5. 3 slag på CS100 — full innsats\n6. Noter CS-nivå der teknikk brøt',
    duration_minutes: 25,
    pyramid_level: 'TEK',
    training_areas: ['TEE'],
    l_phases: ['L-BALL', 'L-AUTO'],
    cs_min: 'CS60',
    cs_max: 'CS100',
    environments: ['M1', 'M2'],
    press_levels: ['PR2'],
    p_positions: ['P5.0', 'P6.0', 'P7.0'],
    life_codes: ['LIFE-EMO'],
    min_category: 'F',
    max_category: 'A',
    difficulty: 'regional',
    equipment: ['Driver', 'TrackMan eller launch monitor'],
    players_min: 1, players_max: 1,
    trackman_metrics: ['club_speed', 'ball_speed', 'smash_factor', 'face_angle', 'club_path'],
    source: 'ak_original',
    tags: ['speed-ladder', 'breaking-point', 'driver', 'overføring'],
    sg_area: 'tee',
    is_approved: true,
  },

  // ── TEK: NÆRSPILL ────────────────────────────────────────

  {
    name: 'Chip landing zone — 3 soner',
    description: 'Plasser 3 håndklær på 3, 5 og 8 meter. Chip med PW/9-jern mot hver sone. 10 baller per sone. Score 3 poeng for treff, 1 for innen 1m.',
    goal: 'Utvikle avstandskontroll og konsistent landing med chip',
    instructions: '1. Legg håndklær på 3m, 5m og 8m fra green edge\n2. Start med PW mot 3m: 10 baller\n3. Bytt til 5m: 10 baller\n4. Bytt til 8m: 10 baller\n5. Score: 3p treff håndkle, 1p innen 1m\n6. Mål: 15+ poeng per sone',
    duration_minutes: 20,
    pyramid_level: 'TEK',
    training_areas: ['CHIP'],
    l_phases: ['L-BALL'],
    cs_min: 'CS40',
    cs_max: 'CS60',
    environments: ['M3'],
    press_levels: ['PR2'],
    p_positions: ['P7.0', 'P8.0'],
    life_codes: ['LIFE-SELV'],
    min_category: 'K',
    max_category: 'A',
    difficulty: 'nybegynner',
    equipment: ['PW', '9-jern', '3 håndklær', 'Baller'],
    players_min: 1, players_max: 4,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['chip', 'landing-zone', 'avstandskontroll'],
    sg_area: 'short_game',
    is_approved: true,
  },
  {
    name: 'Bunker: Linje i sanden',
    description: 'Trekk linje i sanden. Slå bunkerslag der du treffer sanden PÅ linjen (ikke ballen). Fokus på å entre sanden konsistent 3-5cm bak ballen.',
    goal: 'Konsistent sandkontakt i bunker',
    instructions: '1. Trekk lang linje i sanden\n2. Ingen ball først — slå 10 slag langs linjen\n3. Sjekk: treffer du linjen hver gang?\n4. Legg ball 3-5cm foran linjen\n5. Slå 10 bunkerslag — entre på linjen\n6. Mål: 8/10 treff innen 5m av hull',
    duration_minutes: 15,
    pyramid_level: 'TEK',
    training_areas: ['BUNKER'],
    l_phases: ['L-KØLLE', 'L-BALL'],
    cs_min: 'CS40',
    cs_max: 'CS70',
    environments: ['M3'],
    press_levels: ['PR1', 'PR2'],
    p_positions: ['P6.0', 'P7.0', 'P8.0'],
    min_category: 'J',
    max_category: 'A',
    difficulty: 'rekrutt',
    equipment: ['Sand wedge', 'Baller'],
    players_min: 1, players_max: 4,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['bunker', 'sandkontakt', 'konsistens'],
    sg_area: 'short_game',
    is_approved: true,
  },

  // ── TEK: PUTTING ──────────────────────────────────────────

  {
    name: 'Gate drill — 3 fot putting',
    description: '2 tees som gate akkurat bredere enn putthodet. 3 fot fra hull. 20 putts gjennom gaten. Mål: 18/20.',
    goal: 'Konsistent startlinje på korte putts',
    instructions: '1. Sett 2 tees som gate, 1cm bredere enn putterhodet\n2. Plasser ball 3 fot fra hull med rett putt\n3. 20 putts gjennom gaten\n4. Tell treff: mål 18/20\n5. Hvis <15: smalere gate. Hvis >18: øk til 5 fot',
    duration_minutes: 10,
    pyramid_level: 'TEK',
    training_areas: ['PUTT0-3', 'PUTT3-5'],
    l_phases: ['L-BALL'],
    environments: ['M3'],
    press_levels: ['PR2'],
    life_codes: ['LIFE-SELV'],
    min_category: 'K',
    max_category: 'A',
    difficulty: 'nybegynner',
    equipment: ['Putter', '2 tees', 'Ball'],
    players_min: 1, players_max: 4,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['putting', 'gate-drill', 'startlinje', 'kort-putt'],
    sg_area: 'putting',
    is_approved: true,
  },
  {
    name: 'Speed control: 4-kvadrant lag putt',
    description: 'Putt fra 30 fot mot hull. Ballen skal stoppe i en "dødsone" — maks 2 fot forbi, aldri kort. 4 retninger (opp, ned, venstre break, høyre break).',
    goal: 'Lengdekontroll på lange putts fra alle retninger',
    instructions: '1. Finn hull med plass rundt\n2. Plasser ball 30 fot unna — rett opp bakken\n3. 5 putts: alle skal stoppe 0-2 fot forbi\n4. Flytt til nedover: 5 putts\n5. Venstre break: 5 putts\n6. Høyre break: 5 putts\n7. Score: antall i dødsonen av 20',
    duration_minutes: 20,
    pyramid_level: 'TEK',
    training_areas: ['PUTT25-40'],
    l_phases: ['L-BALL'],
    environments: ['M3'],
    press_levels: ['PR2', 'PR3'],
    life_codes: ['LIFE-EMO'],
    min_category: 'H',
    max_category: 'A',
    difficulty: 'klubb',
    equipment: ['Putter', 'Ball'],
    players_min: 1, players_max: 4,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['putting', 'speed-control', 'lag-putt', 'lengdekontroll'],
    sg_area: 'putting',
    is_approved: true,
  },

  // ── SLAG: Måltrening ──────────────────────────────────────

  {
    name: 'Innspill 100m — Nærmest hull (10 baller)',
    description: 'Velg et 100m mål. Slå 10 baller med full rutine mellom hvert slag. Mål avstand til mål. CS70-80.',
    goal: 'Presisjon på approach-slag med turneringslignende rutine',
    instructions: '1. Velg mål på 100m\n2. Full pre-shot rutine før hvert slag\n3. 10 baller, noter avstand til mål\n4. Beregn snittavstand\n5. Mål: C-D <5.5m, E-F <7m, G-H <9m',
    duration_minutes: 20,
    pyramid_level: 'SLAG',
    training_areas: ['INN100'],
    l_phases: ['L-BALL', 'L-AUTO'],
    cs_min: 'CS70',
    cs_max: 'CS90',
    environments: ['M2'],
    press_levels: ['PR2', 'PR3'],
    life_codes: ['LIFE-SELV'],
    min_category: 'G',
    max_category: 'A',
    difficulty: 'klubb',
    equipment: ['Wedge/kort jern', 'Baller', 'Avstandsmåler'],
    players_min: 1, players_max: 6,
    trackman_metrics: ['carry_distance', 'lateral_landing', 'landing_angle'],
    source: 'ak_original',
    tags: ['innspill', 'presisjon', 'måltrening', 'approach'],
    sg_area: 'approach',
    is_approved: true,
  },
  {
    name: 'Driver — Fairway-boks',
    description: 'Sett opp to mål som markerer en "fairway" på 30m bredde. 10 driver-slag. Score: 2p fairway, 1p innen 10m av kant, 0p miss.',
    goal: 'Trene driver-presisjon mot realistisk fairway-bredde',
    instructions: '1. Identifiser to mål 30m fra hverandre som "fairway"\n2. Full rutine, CS80+\n3. 10 slag, score hvert\n4. 2p = fairway, 1p = innen 10m, 0p = miss\n5. Mål: 14+ poeng',
    duration_minutes: 20,
    pyramid_level: 'SLAG',
    training_areas: ['TEE'],
    l_phases: ['L-AUTO'],
    cs_min: 'CS80',
    cs_max: 'CS100',
    environments: ['M2'],
    press_levels: ['PR3', 'PR4'],
    life_codes: ['LIFE-EMO', 'LIFE-KAR'],
    min_category: 'F',
    max_category: 'A',
    difficulty: 'klubb',
    equipment: ['Driver', 'Baller', 'Mål/flagg'],
    players_min: 1, players_max: 6,
    trackman_metrics: ['carry_distance', 'lateral_landing', 'face_angle', 'club_path'],
    source: 'ak_original',
    tags: ['driver', 'fairway', 'presisjon', 'scoring'],
    sg_area: 'tee',
    is_approved: true,
  },

  // ── SPILL: Strategi ───────────────────────────────────────

  {
    name: '9-hull strategirunde',
    description: 'Treningsrunde med fokus på beslutninger, ikke score. Før hvert slag: velg strategi og si den høyt. Etter runde: gjennomgang av alle valg.',
    goal: 'Utvikle bevisst kursmanagement og beslutningskvalitet',
    instructions: '1. Start 9 hull med spillkortong\n2. Før HVERT slag: si strategien høyt\n3. "Jeg spiller mot midten av green fordi flagget står bak bunker"\n4. Noter alle beslutninger\n5. Etter runde: gå gjennom — var valget riktig?\n6. Score er irrelevant — beslutningskvalitet er målet',
    duration_minutes: 90,
    pyramid_level: 'SPILL',
    training_areas: ['TEE', 'INN200', 'INN150', 'INN100'],
    l_phases: ['L-AUTO'],
    cs_min: 'CS80',
    cs_max: 'CS100',
    environments: ['M4'],
    press_levels: ['PR3'],
    life_codes: ['LIFE-SELV', 'LIFE-KAR'],
    min_category: 'G',
    max_category: 'A',
    difficulty: 'klubb',
    equipment: ['Full bag', 'Notatblokk'],
    players_min: 1, players_max: 4,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['strategi', 'kursmanagement', 'beslutning', 'treningsrunde'],
    sg_area: 'approach',
    is_approved: true,
  },

  // ── FYS ───────────────────────────────────────────────────

  {
    name: 'Golf-spesifikk oppvarming (dynamisk)',
    description: 'Standard oppvarmingsrutine for alle økter. Dynamisk tøying, rotasjonsøvelser, golfspesifikk aktivering. 8-10 minutter.',
    goal: 'Forberede kroppen på golftrening, redusere skaderisiko',
    instructions: '1. Arm-sirkler 10x hver retning\n2. Hofterotasjon med kølle bak rygg 10x\n3. Lunges med rotasjon 5x per side\n4. Skuldertøying med kølle overhead 10x\n5. Halvsvinger uten ball CS30, økende til CS50\n6. 5 fulle svinger CS60',
    duration_minutes: 10,
    pyramid_level: 'FYS',
    training_areas: ['TEE'],
    l_phases: ['L-KROPP'],
    cs_min: 'CS0',
    cs_max: 'CS0',
    environments: ['M0', 'M1', 'M2', 'M3'],
    press_levels: ['PR1'],
    min_category: 'K',
    max_category: 'A',
    difficulty: 'nybegynner',
    equipment: ['Golf-kølle (valgfri)'],
    players_min: 1, players_max: 20,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['oppvarming', 'dynamisk', 'mobilitet', 'standard'],
    is_approved: true,
  },
  {
    name: 'Kjernetrening for rotasjonskraft',
    description: 'Medisinball-rotasjon, planke med rotasjon, cable woodchops. Fokus på kraft gjennom rotasjon — direkte overførbar til sving.',
    goal: 'Bygge rotasjonskraft i kjernemuskulatur',
    instructions: '1. Medisinball siderotasjon mot vegg: 3×10 per side\n2. Planke med hofterotasjon: 3×8 per side\n3. Cable woodchop eller band: 3×12 per side\n4. Russian twist med vekt: 3×15\n5. 60 sek hvile mellom sett',
    duration_minutes: 25,
    pyramid_level: 'FYS',
    training_areas: ['TEE'],
    l_phases: ['L-KROPP'],
    cs_min: 'CS0',
    cs_max: 'CS0',
    environments: ['M0'],
    press_levels: ['PR1'],
    life_codes: ['LIFE-SELV'],
    min_category: 'G',
    max_category: 'A',
    difficulty: 'klubb',
    equipment: ['Medisinball', 'Matte', 'Kabel/strikk'],
    players_min: 1, players_max: 6,
    trackman_metrics: ['club_speed'],
    source: 'ak_original',
    tags: ['styrke', 'rotasjon', 'kjerne', 'power'],
    is_approved: true,
  },

  // ── TURN: Mental ──────────────────────────────────────────

  {
    name: 'Pre-shot rutine drill — konsistenstest',
    description: 'Film pre-shot rutinen 10 ganger. Mål tid for hver. Mål: <2 sek variasjon. Bygg automatikk.',
    goal: 'Konsistent pre-shot rutine som fungerer under press',
    instructions: '1. Sett opp kamera\n2. Full pre-shot rutine → slag, 10 ganger\n3. Se video: noter tid per rutine\n4. Mål: maks 2 sek variasjon\n5. Identifiser hva som endrer seg\n6. Gjenta til konsistent',
    duration_minutes: 20,
    pyramid_level: 'TURN',
    training_areas: ['TEE', 'INN150'],
    l_phases: ['L-AUTO'],
    cs_min: 'CS80',
    cs_max: 'CS100',
    environments: ['M2', 'M4'],
    press_levels: ['PR3', 'PR4'],
    life_codes: ['LIFE-SELV', 'LIFE-RES'],
    min_category: 'F',
    max_category: 'A',
    difficulty: 'regional',
    equipment: ['Kamera/mobil', 'Full bag'],
    players_min: 1, players_max: 2,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['pre-shot', 'rutine', 'mental', 'konsistens', 'turnering'],
    is_approved: true,
  },

  // ── LEKBASERTE (J-K) ─────────────────────────────────────

  {
    name: 'Golf-bowling (J-K)',
    description: 'Sett opp "bowlingkjegler" av plastflasker. Barna ruller/chipper ball for å slå ned flest. Lek med golf-elementer.',
    goal: 'Introdusere golf gjennom lek — motorikk og gøy',
    instructions: '1. Sett opp 6 plastflasker i trekant\n2. 5 meter avstand\n3. Hvert barn får 3 forsøk\n4. Rulle med putter ELLER chip med wedge\n5. Poeng per flaske\n6. 3 runder, tell poeng',
    duration_minutes: 15,
    pyramid_level: 'TEK',
    training_areas: ['CHIP', 'PUTT0-3'],
    l_phases: ['L-KROPP', 'L-ARM'],
    cs_min: 'CS0',
    cs_max: 'CS30',
    environments: ['M1', 'M3'],
    press_levels: ['PR1', 'PR3'],
    life_codes: ['LIFE-SOS', 'LIFE-KAR'],
    min_category: 'K',
    max_category: 'J',
    difficulty: 'nybegynner',
    equipment: ['Putter', 'Plastflasker', 'Baller'],
    players_min: 2, players_max: 8,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['lek', 'knøtt', 'motorikk', 'bowling', 'sosialt'],
    sg_area: 'short_game',
    is_approved: true,
  },
  {
    name: 'Putting-hinderløype (J-K)',
    description: 'Sett opp 6 "hull" med hindre (tunneler, ramper, bøyler). Barna putter gjennom hele løypa. Minigolf-følelse.',
    goal: 'Grunnleggende putting-ferdighet gjennom lekbasert trening',
    instructions: '1. Bygg 6 stasjoner med hindre\n2. Barna putter fra stasjon til stasjon\n3. Tell slag per stasjon\n4. Total score for hele løypa\n5. Gjenta 2 ganger — prøv å slå egen score',
    duration_minutes: 20,
    pyramid_level: 'TEK',
    training_areas: ['PUTT0-3', 'PUTT3-5'],
    l_phases: ['L-BALL'],
    cs_min: 'CS0',
    cs_max: 'CS30',
    environments: ['M1', 'M3'],
    press_levels: ['PR1', 'PR3'],
    life_codes: ['LIFE-SOS', 'LIFE-EMO'],
    min_category: 'K',
    max_category: 'I',
    difficulty: 'nybegynner',
    equipment: ['Putter', 'Baller', 'Hindre/tunneler'],
    players_min: 2, players_max: 8,
    trackman_metrics: [],
    source: 'ak_original',
    tags: ['lek', 'knøtt', 'putting', 'hinderløype', 'minigolf'],
    sg_area: 'putting',
    is_approved: true,
  },

  // ── KONKURRANSE-DRILLER (PR4) ─────────────────────────────

  {
    name: 'Nærmest hull — 5 baller lagkonkurranse',
    description: '2 lag, 5 baller hver. Innspill mot flagg fra 100-150m. Laget med lavest total avstand vinner. PR4.',
    goal: 'Presisjon under sosialt press med konkurranseelement',
    instructions: '1. Del i 2 lag\n2. Velg innspillavstand (100-150m)\n3. Hvert lag slår 5 baller\n4. Mål avstand til hull for hver ball\n5. Summer avstand per lag\n6. Lavest total vinner\n7. Taperlaget velger neste øvelse',
    duration_minutes: 15,
    pyramid_level: 'SLAG',
    training_areas: ['INN100', 'INN150'],
    l_phases: ['L-AUTO'],
    cs_min: 'CS70',
    cs_max: 'CS90',
    environments: ['M2'],
    press_levels: ['PR4'],
    life_codes: ['LIFE-EMO', 'LIFE-KAR'],
    min_category: 'G',
    max_category: 'A',
    difficulty: 'klubb',
    equipment: ['Jern/wedge', 'Baller', 'Avstandsmåler'],
    players_min: 4, players_max: 8,
    trackman_metrics: ['carry_distance', 'lateral_landing'],
    source: 'ak_original',
    tags: ['konkurranse', 'lag', 'innspill', 'press', 'PR4'],
    sg_area: 'approach',
    is_approved: true,
  },
];

async function seed() {
  console.log(`Seeder ${drills.length} AK-original driller...`);

  const { data, error } = await sb.from('drills').insert(drills).select('id, name');

  if (error) {
    console.error('Feil ved seeding:', error.message);
    process.exit(1);
  }

  console.log(`✓ ${data.length} driller lagt til:`);
  for (const d of data) {
    console.log(`  ${d.name}`);
  }

  // Stats
  const pyramidCount: Record<string, number> = {};
  for (const d of drills) {
    pyramidCount[d.pyramid_level] = (pyramidCount[d.pyramid_level] ?? 0) + 1;
  }
  console.log('\nFordeling:');
  for (const [k, v] of Object.entries(pyramidCount)) {
    console.log(`  ${k}: ${v}`);
  }

  console.log('\nNeste steg: Kjør ak_drill_coverage_gaps for å se hva som mangler.');
}

seed();
